version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    ports:
      - "8001:8000"
    environment:
      - NODE_ID=1
      - SHARD_ID=0
      - GOSSIP_PEERS=http://node2:8000,http://node3:8000
      - ALL_PEERS=http://node1:8000,http://node2:8000,http://node3:8000
      - ALL_PEERS_IDS=1,2,3
    networks:
      - gossip_network
    mem_limit: 256M

  node2:
    build: .
    container_name: node2
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=2
      - SHARD_ID=1
      - GOSSIP_PEERS=http://node1:8000,http://node3:8000
      - ALL_PEERS=http://node1:8000,http://node2:8000,http://node3:8000
      - ALL_PEERS_IDS=1,2,3
    networks:
      - gossip_network
    mem_limit: 256M

  node3:
    build: .
    container_name: node3
    ports:
      - "8003:8000"
    environment:
      - NODE_ID=3
      - SHARD_ID=2
      - GOSSIP_PEERS=http://node1:8000,http://node2:8000
      - ALL_PEERS=http://node1:8000,http://node2:8000,http://node3:8000
      - ALL_PEERS_IDS=1,2,3
    networks:
      - gossip_network
    mem_limit: 256M
    
networks:
  gossip_network:
    driver: bridge